flood_relief_center/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "flood-relief-center"
urlpatterns = [
    path("", views.index, name="index"),

    path("donations/", views.DonationListView.as_view(), name="donations"),
    path("add-donation/", views.add_donation, name="add-donation"),
    path("edit-donation/<int:donationID>/", views.edit_donation, name="edit-donation"),
    path("delete-donation/<int:donationID>/", views.delete_donation, name="delete-donation"),

    path("relief-centers/", views.ReliefCentersListView.as_view(), name="relief-centers"),
    path("relief-centers/<int:centerID>/", views.ReliefCenterDetailView.as_view(), name="relief-center-detail"),
    path("add-relief-center/", views.add_relief_center, name="add-relief-center"),
    path("edit-relief-center/<int:centerID>/", views.edit_relief_center, name="edit-relief-center"),
    path("delete-relief-center/<int:centerID>/", views.delete_relief_center, name="delete-relief-center"),

    path("victims/", views.VictimsListView.as_view(), name="victims"),
    path("edit-victim/<int:victimID>/", views.edit_victim, name="edit-victim"),
    path("add-victim", views.add_victim, name="add-victim"),
    path("delete-victim/<int:victimID>/", views.delete_victim, name="delete-victim"),
    path("stats-victims/", views.StatsVictim.as_view(), name="stats-victims"),

    path("volunteers/<int:centerID>/", views.VolunteersListView.as_view(), name="volunteers"),
    path("edit-volunteer/<int:centerID>/<int:volunteerID>/", views.edit_volunteer, name="edit-volunteer"),
    path("add-volunteer/<int:centerID>", views.add_volunteer, name="add-volunteer"),
    path("delete-volunteer/<int:centerID>/<int:volunteerID>/", views.delete_volunteer, name="delete-volunteer"),

    path("affected-areas/", views.AffectedAreaListView.as_view(), name="affected-areas"),
    path("add-affected-area/", views.add_affected_area, name="add-affected-area"),
    path("edit-affected-area/<int:areaID>/", views.edit_affected_area, name="edit-affected-area"),
    path("delete-affected-area/<int:areaID>/", views.delete_affected_area, name="delete-affected-area"),

    
    path("rescue-teams/<int:centerID>/", views.RescueTeamsListView.as_view(), name="rescue-teams"),
    path("add-rescue-team/<int:centerID>/",views.add_rescue_team, name="add-rescue-teams" )

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from flood_relief_center import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('flood_relief_center.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Semantic UI CSS (optional, if needed) -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/semantic.min.css" />

    <!-- Chart.js Library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <!-- jQuery (for Bootstrap JS, not required if not using Bootstrap JS components) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

    <!-- Popper.js (needed for Bootstrap) -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'flood_relief_center/style.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'flood-relief-center:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'flood-relief-center:stats-victims' %}">Victim Stats <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    {% block scripts %}
    {% endblock scripts %}
    <!-- Main content block -->
    {% block content %}
    {% endblock %}

</body>

</html>